[package]
name = "jruby-launcherr"
version = "0.1.0"
authors = ["Thomas E. Enebo <tom.enebo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
log = { version = "0.4.5", features = ["std"] }
libc = "0.2.67"
sys-info = {version = "0.5.10", git = "https://github.com/FillZpp/sys-info-rs.git" }
