fn main() {
    windows::build!(
        Windows::Win32::SystemServices::BOOL,
        Windows::Win32::SystemServices::CreateProcessW,
        Windows::Win32::SystemServices::GetCommandLineW,
        Windows::Win32::SystemServices::GetConsoleWindow,
        Windows::Win32::SystemServices::GetExitCodeProcess,
        Windows::Win32::SystemServices::PROCESS_INFORMATION,
        Windows::Win32::SystemServices::PWSTR,
        Windows::Win32::SystemServices::ResumeThread,
        Windows::Win32::SystemServices::SetConsoleCtrlHandler,
        Windows::Win32::SystemServices::STARTUPINFOW,
        Windows::Win32::SystemServices::WaitForSingleObject,
        Windows::Win32::WindowsAndMessaging::HWND,
        Windows::Win32::WindowsProgramming::CloseHandle,
        Windows::Win32::WindowsProgramming::INFINITE,
        Windows::Win32::WindowsProgramming::PROCESS_CREATION_FLAGS,
        Windows::Win32::WindowsProgramming::uaw_wcslen,
        Windows::Win32::Debug::GetLastError
    );
}